In [3]:
import numpy as np

def crear_y_mostrar_matriz():

  try:
    matriz = np.array([[1, 2, 3],
                      [4, 5, 1],
                      [2, 1, 2]])

    print("Matriz 3x3:")
    print(matriz)

    sumatoria = np.sum(matriz)
    print("\nSumatoria de los elementos de la matriz:", sumatoria)

  except Exception as e:
    print(f"Error: {e}")

# Llamar a la función para ejecutar el código
crear_y_mostrar_matriz()

Matriz 3x3:
[[1 2 3]
 [4 5 1]
 [2 1 2]]

Sumatoria de los elementos de la matriz: 21
